config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  namespace :admin do
    resources :dashboard, only: [ :index ]
    resources :users, only: [ :show, :destroy, :edit, :update, :index, :new, :create ] do
      member do
        delete :delete_profile_image
      end
    end
    resources :roles, only: [ :index, :new, :create, :show, :update, :edit ] do
      resources :user_roles, only: [ :create, :new, :destroy ], module: :roles
      resources :roles_permissions, only: [ :create, :new, :destroy ], module: :roles
    end
  end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "admin/dashboard#index"
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users_roles, dependent: :destroy
  has_many :users, through: :users_roles
  has_many :roles_permissions, dependent: :destroy
  has_many :permissions, through: :roles_permissions

  validates :name, presence: true, uniqueness: true

  scope :with_users_count, -> {
    joins("LEFT JOIN users_roles ON users_roles.role_id = roles.id")
      .select("roles.*, COUNT(DISTINCT users_roles.user_id) AS users_count")
      .group("roles.id")
  }

  scope :with_permissions_count, -> {
    joins("LEFT JOIN roles_permissions ON roles_permissions.role_id = roles.id")
      .select("roles.*, COUNT(DISTINCT roles_permissions.permission_id) AS permissions_count")
      .group("roles.id")
  }

  def self.ransackable_attributes(auth_object = nil)
    [ "name" ]
  end

  def add_users!(user_ids)
    processed_user_ids = Array(user_ids).map(&:to_s).compact_blank.uniq
    return if processed_user_ids.empty?

    current_user_ids = self.user_ids.map(&:to_s)
    ids_to_add = processed_user_ids - current_user_ids

    return if ids_to_add.empty?

    self.users << User.where(id: ids_to_add)
  end

  def add_permissions!(permission_ids)
    processed_permission_ids = Array(permission_ids).map(&:to_s).compact_blank.uniq
    return if processed_permission_ids.empty?

    current_permission_ids = self.permission_ids.map(&:to_s)
    ids_to_add = processed_permission_ids - current_permission_ids

    return if ids_to_add.empty?

    self.permissions << Permission.where(id: ids_to_add)
  end
end

app/models/roles_permission.rb
class RolesPermission < ApplicationRecord
  belongs_to :role
  belongs_to :permission
end

app/controllers/admin/roles/roles_permissions_controller.rb
class Admin::Roles::RolesPermissionsController < Admin::BaseController
  load_resource :role, class: "Role", id_param: :role_id
  authorize_resource :roles_permission, class: "RolesPermission"

  def new
    # Display modal with permissions list that can be added to the role

    result = PermissionsWithoutRoleQuery.call(
      role:   @role,
      params: params[:q],
      per_page: params[:per_page],
      page:   params[:page]
    )

    @permissions_available = result[:permissions]
    @q = result[:search]

    render turbo_stream: turbo_stream.replace(
      "permissions_list",
      partial: "admin/roles/roles_permissions/permissions_list",
      locals: { role: @role, permissions_available: @permissions_available, q: @q }
    )
  end

  def create
    @role.add_permissions!(role_params[:permission_ids])
    redirect_to admin_role_path(@role), notice: t("admin.roles.add_role_to_permissions.success", count: role_params[:permission_ids].size, role_name: @role.name)
  end

  def destroy
    @role_permission = RolesPermission.find(params[:id])

    if @role_permission.destroy
      redirect_to admin_role_path(@role), notice: t("admin.roles.remove_permission.success", role_name: @role.name)
    else
      redirect_to admin_role_path(@role), alert: @role_permission.errors.full_messages.to_sentence
    end
  end

  private

  def role_params
    params.require(:role_permission).permit(permission_ids: [])
  end
end

app/controllers/admin/roles/user_roles_controller.rb
class Admin::Roles::UserRolesController < Admin::BaseController
  load_resource :role, class: "Role", id_param: :role_id
  authorize_resource :user_role, class: "UsersRole"

  def new
    # Display modal with users list that can be added to the role

    result = UsersWithoutRoleQuery.call(
      role:   @role,
      params: params[:q],
      per_page: params[:per_page],
      page:   params[:page]
    )

    @users_available = result[:users]
    @q = result[:search]

    render turbo_stream: turbo_stream.replace(
      "users_list",
      partial: "admin/roles/user_roles/users_list",
      locals: { role: @role, users_available: @users_available, q: @q }
    )
  end

  def create
    @role.add_users!(role_params[:user_ids])
    redirect_to admin_role_path(@role), notice: t("admin.roles.add_role_to_users.success", count: role_params[:user_ids].size, role_name: @role.name)
  end

  def destroy
    @users_role = UsersRole.find(params[:id])

    if @users_role.destroy
      redirect_to admin_role_path(@role), notice: t("admin.user_roles.user_removed", role_name: @role.name)
    else
      redirect_to admin_role_path(@role), alert: @users_role.errors.full_messages.to_sentence
    end
  end

  private

  def role_params
    params.require(:role_user).permit(user_ids: [])
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::BaseController
  load_and_authorize_resource

  def index
    @roles = Role.with_users_count
  end

  def show
    @role = Role.with_users_count.with_permissions_count.includes(users_roles: :user, roles_permissions: :permission).find(params[:id])
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to admin_roles_path, notice: t("admin.roles.create.success")
    else
      flash.now[:error] = @role.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    render turbo_stream: turbo_stream.replace(
      "role_basic_info_#{@role.id}",
      partial: "admin/roles/basic_infos/form",
      locals: { role: @role }
    )
  end

  def update
    if @role.update(role_params)
      redirect_to admin_role_path(@role), notice: t("admin.roles.update.success")
    else
      flash.now[:error] = t("admin.users.update.failure", errors: @role.errors.full_messages.join(", "))

      render turbo_stream: turbo_stream.replace(
        "role_basic_info_#{@role.id}",
        partial: "admin/roles/basic_infos/form",
        locals: { role: @role }
      ), status: :unprocessable_entity
    end
  end

  private

  def role_params
    params.require(:role).permit(:name, :color)
  end
end

app/views/admin/roles/roles_permissions/_new.html.erb
<dialog id="add_permissions_modal_<%= @role.id %>" class="modal modal-bottom sm:modal-middle">
    <div class="modal-box relative">
        <%= render "shared/flash_error" %>

        <form method="dialog">
            <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">
                <i class="fa-solid fa-xmark text-xl"></i>
            </button>
        </form>

        <h3 class="font-bold text-lg mb-1">
        <%= t("admin.roles.add_permissions.title") %>
        </h3>

        <p class="text-sm mb-4">
        <%= t("admin.roles.add_permissions.subtitle", role_name: role.decorate.name) %>
        </p>
        
        <turbo-frame id="permissions_list" src="<%= new_admin_role_roles_permission_path(@role) %>">
        </turbo-frame>
    </div>
</dialog>

app/views/admin/roles/roles_permissions/_permissions_list.html.erb
<turbo-frame id="permissions_list">
    <%= search_form_for @q,
        url:    new_admin_role_roles_permission_path(role),
        html:   {
            class:      "w-full max-w-4xl mb-6 mx-auto",
            data:       { turbo_frame: "permissions_list" }
        } do |f| %>
        <div class="flex flex-col gap-2 w-full">
            <div class="overflow-x-auto flex items-center gap-2 w-full">
                <label class="input input-bordered flex items-center gap-2 grow">
                <i class="fas fa-search"></i>
                <%= f.search_field :name_cont,
                        placeholder: t("admin.permissions.search.placeholder"),
                        class:       "bg-transparent outline-none w-full" %>
                </label>
            </div>

            <div class="flex items-center gap-2">
                <%= label_tag :per_page, "#{t("common.per_page")}:" %>
                <%= select_tag :per_page, options_for_select([10, 20, 50, 100], params[:per_page].presence || PermissionsWithoutRoleQuery::DEFAULT_PER_PAGE), placeholder: t("admin.common.per_page"), onchange: "this.form.requestSubmit()", class: "select select-bordered" %>
            </div>
        </div>
    <% end %>

        <%= form_with model: [role, RolesPermission.new],
                    url:   admin_role_roles_permissions_path(role),
                    scope: :role_permission,
                    method: :post,
                    data:  { turbo_frame: "main", controller: "select-all enable-submit-button" } do |form| %>

        <% if permissions_available.any? %>

            <div class="mb-4 flex items-center justify-end gap-2">
                <%= label_tag "select_all", t("common.select_all") %>
                <%= check_box_tag "select_all", "1", false,
                    class: "checkbox checkbox-accent",
                    data: {
                        action: "select-all#toggleAll",
                        "select-all-target": "master",
                        "enable-submit-button-target": "checkbox"
                    } %>
            </div>

            <% permissions_available.each do |permission| %>
                <div class="bg-base-200 rounded-lg p-4 flex items-center justify-between">
                <div class="flex items-center space-x-3">
                    <div class="text-sm font-medium"><%= permission.name.titleize %></div>
                </div>
                <%= form.check_box :permission_ids,
                    { multiple: true,
                        class: "checkbox checkbox-accent",
                        data:  { "enable-submit-button-target": "checkbox", "select-all-target": "checkbox" }
                    },
                    permission.id,
                    nil %>
                </div>
            <% end %>

            <div class="flex justify-end mt-4">
                    <%= form.submit t("admin.roles.permissions_list.add_selected_permissions"),
                                    class: "btn btn-accent btn-soft", disabled: true, data: { "enable-submit-button-target": "submitButton" } %>
            </div>
        <% else %>
          <div class="alert alert-info shadow-lg">
            <div>
              <i class="fas fa-shield-alt"></i>
              <span><%= t("admin.roles.permissions_list.no_permissions_available") %></span>
            </div>
          </div>
        <% end %>
        <%= render PaginationComponent.new(collection: permissions_available) %>
        <% end %>
</turbo-frame>