config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check


  namespace :admin do
    resources :dashboard, only: [ :index ]
    resources :users, only: [ :show, :destroy, :edit, :update, :index, :new, :create ] do
      member do
        delete :delete_profile_image
      end
    end
    resources :roles, only: [ :index, :new, :create, :show, :update, :edit ] do
      resources :user_roles, only: [ :create, :new, :destroy ], module: :roles
      resources :roles_permissions, only: [ :create, :new, :destroy ], module: :roles
    end
  end

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "admin/dashboard#index"
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users_roles, dependent: :destroy
  has_many :users, through: :users_roles
  has_many :roles_permissions, dependent: :destroy
  has_many :permissions, through: :roles_permissions

  validates :name, presence: true, uniqueness: true

  scope :with_users_count, -> {
    joins("LEFT JOIN users_roles ON users_roles.role_id = roles.id")
      .select("roles.*, COUNT(DISTINCT users_roles.user_id) AS users_count")
      .group("roles.id")
  }

  scope :with_permissions_count, -> {
    joins("LEFT JOIN roles_permissions ON roles_permissions.role_id = roles.id")
      .select("roles.*, COUNT(DISTINCT roles_permissions.permission_id) AS permissions_count")
      .group("roles.id")
  }

  def self.ransackable_attributes(auth_object = nil)
    [ "name" ]
  end

  def add_users!(user_ids)
    processed_user_ids = Array(user_ids).map(&:to_s).compact_blank.uniq
    return if processed_user_ids.empty?

    current_user_ids = self.user_ids.map(&:to_s)
    ids_to_add = processed_user_ids - current_user_ids

    return if ids_to_add.empty?

    self.users << User.where(id: ids_to_add)
  end

  def add_permissions!(permission_ids)
    processed_permission_ids = Array(permission_ids).map(&:to_s).compact_blank.uniq
    return if processed_permission_ids.empty?

    current_permission_ids = self.permission_ids.map(&:to_s)
    ids_to_add = processed_permission_ids - current_permission_ids

    return if ids_to_add.empty?

    self.permissions << Permission.where(id: ids_to_add)
  end
end

app/controllers/admin/roles/roles_permissions_controller.rb
class Admin::Roles::RolesPermissionsController < Admin::BaseController
  load_resource :role, class: "Role", id_param: :role_id
  authorize_resource :roles_permission, class: "RolesPermission"

  def new
    # Display modal with permissions list that can be added to the role

    result = PermissionsWithoutRoleQuery.call(
      role:   @role,
      params: params[:q],
      per_page: params[:per_page],
      page:   params[:page]
    )

    @permissions_available = result[:permissions]
    @q = result[:search]

    render turbo_stream: turbo_stream.replace(
      "permissions_list",
      partial: "admin/roles/roles_permissions/permissions_list",
      locals: { role: @role, permissions_available: @permissions_available, q: @q }
    )
  end

  def create
    @role.add_permissions!(role_params[:permission_ids])
    redirect_to admin_role_path(@role), notice: t("admin.roles.add_role_to_permissions.success", count: role_params[:permission_ids].size, role_name: @role.name)
  end

  def destroy
    @role_permission = RolesPermission.find(params[:id])

    if @role_permission.destroy
      redirect_to admin_role_path(@role), notice: t("admin.roles.remove_permission.success", role_name: @role.name)
    else
      redirect_to admin_role_path(@role), alert: @role_permission.errors.full_messages.to_sentence
    end
  end

  private

  def role_params
    params.require(:role_permission).permit(permission_ids: [])
  end
end

app/controllers/admin/roles/user_roles_controller.rb
class Admin::Roles::UserRolesController < Admin::BaseController
  load_resource :role, class: "Role", id_param: :role_id
  authorize_resource :user_role, class: "UsersRole"

  def new
    # Display modal with users list that can be added to the role

    result = UsersWithoutRoleQuery.call(
      role:   @role,
      params: params[:q],
      per_page: params[:per_page],
      page:   params[:page]
    )

    @users_available = result[:users]
    @q = result[:search]

    render turbo_stream: turbo_stream.replace(
      "users_list",
      partial: "admin/roles/user_roles/users_list",
      locals: { role: @role, users_available: @users_available, q: @q }
    )
  end

  def create
    @role.add_users!(role_params[:user_ids])
    redirect_to admin_role_path(@role), notice: t("admin.roles.add_role_to_users.success", count: role_params[:user_ids].size, role_name: @role.name)
  end

  def destroy
    @users_role = UsersRole.find(params[:id])

    if @users_role.destroy
      redirect_to admin_role_path(@role), notice: t("admin.user_roles.user_removed", role_name: @role.name)
    else
      redirect_to admin_role_path(@role), alert: @users_role.errors.full_messages.to_sentence
    end
  end

  private

  def role_params
    params.require(:role_user).permit(user_ids: [])
  end
end

app/controllers/admin/roles_controller.rb
class Admin::RolesController < Admin::BaseController
  load_and_authorize_resource

  def index
    @roles = Role.with_users_count
  end

  def show
    @role = Role.with_users_count.with_permissions_count.includes(users_roles: :user, roles_permissions: :permission).find(params[:id])
  end

  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params)

    if @role.save
      redirect_to admin_roles_path, notice: t("admin.roles.create.success")
    else
      flash.now[:error] = @role.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    render turbo_stream: turbo_stream.replace(
      "role_basic_info_#{@role.id}",
      partial: "admin/roles/basic_infos/form",
      locals: { role: @role }
    )
  end

  def update
    if @role.update(role_params)
      redirect_to admin_role_path(@role), notice: t("admin.roles.update.success")
    else
      flash.now[:error] = t("admin.users.update.failure", errors: @role.errors.full_messages.join(", "))

      render turbo_stream: turbo_stream.replace(
        "role_basic_info_#{@role.id}",
        partial: "admin/roles/basic_infos/form",
        locals: { role: @role }
      ), status: :unprocessable_entity
    end
  end

  private

  def role_params
    params.require(:role).permit(:name, :color)
  end
end

app/views/admin/roles/_add_users_modal.html.erb
<dialog id="add_users_modal_<%= @role.id %>" class="modal modal-bottom sm:modal-middle">
    <div class="modal-box relative">
        <%= render "shared/flash_error" %>

        <form method="dialog">
            <button class="btn btn-sm btn-circle btn-ghost absolute right-2 top-2">
                <i class="fa-solid fa-xmark text-xl"></i>
            </button>
        </form>

        <h3 class="font-bold text-lg mb-1">
        <%= t("admin.roles.add_users.title") %>
        </h3>

        <p class="text-sm mb-4">
        <%= t("admin.roles.add_users.subtitle", role_name: role.decorate.name) %>
        </p>
        
        <turbo-frame id="users_list" src="<%= new_admin_role_user_role_path(@role) %>">
        </turbo-frame>
    </div>
</dialog>

app/views/admin/roles/index.html.erb
<div class="flex justify-between items-center mb-6">
  <div>
    <h1 class="text-2xl font-bold mb-2">
      <%= t("admin.roles.index.title") %>
    </h1>

    <p class="text-l mb-6 subtitle">
      <%= t("admin.roles.index.subtitle") %>
    </p>
  </div>

  <div class="mb-6">
    <%= link_to new_admin_role_path, data: { turbo_frame: "main", turbo_action: "advance" }, class: "btn btn-accent" do %>
      <i class="fas fa-plus mr-2"></i>
      <%= t("admin.roles.index.add_new_role") %>
    <% end %>
  </div>
</div>

<div class="container mx-auto">
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
    <% @roles.each do |role| %>
      <div class="card bg-base-100 shadow-xl border border-base-300">
        <div class="card-body">
          <h2 class="card-title text-xl font-semibold"><%= role.name.capitalize %></h2>
          
          <div class="divider my-2"></div>
          
          <div class="flex justify-between items-end">
            <div class="text-sm text-gray-600">
              <%= t('admin.roles.users_count', count: role.users_count) %>
            </div>
            
            <div class="card-actions justify-end">
              <%= link_to t('common.manage'), admin_role_path(role), class: 'btn btn-sm btn-accent btn-outline', data: { turbo_frame: "main", turbo_action: "advance" } %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/roles/new.html.erb
<h1 class="text-2xl font-bold mb-2">
    <%= t("admin.roles.new.title") %>
</h1>

<p class="text-l mb-6 subtitle">
    <%= t("admin.roles.new.subtitle") %>
</p>
    
<div class="md:w-2/3 w-full">
  <%= render 'admin/roles/basic_infos/form', role: @role %>
</div>

app/views/admin/roles/show.html.erb
<div id="role_name_<%= @role.id %>">
  <h1 class="text-2xl font-bold mb-2">
      <%= t("admin.roles.show.title", role_name: @role.decorate.name) %>
  </h1>
</div>

<p class="text-l mb-6 subtitle">
    <%= t("admin.roles.show.subtitle") %>
</p>



<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
  <div class="bg-base-100 shadow overflow-hidden rounded-lg p-4">
    <div class="flex justify-between items-center mb-4">
      <h3 class="text-lg leading-6 font-medium">
          <%= t("admin.roles.show.basic_information") %>
      </h3>
      <% if can? :update, @role %> 
        <div class="flex space-x-1">
          <%= link_to edit_admin_role_path(@role),
                    data: { turbo_frame: "role_basic_info", turbo_prefetch: "false" },
                    class: "btn btn-accent btn-outline" do %>
            <i class="fa-solid fa-pencil"></i>
            Edit
          <% end %>
        </div>
      <% end %>
    </div>

    <turbo-frame id="role_basic_info_<%= @role.id %>">
      <%= render "admin/roles/basic_infos/plaintext", role: @role %>
    </turbo-frame>
  </div>

  <div class="bg-base-100 shadow rounded-lg p-4 grid grid-cols-1 gap-4">
    <h3 class="text-lg leading-6 font-medium">
        <%= t(".statistics_title") %>
    </h3>

    <div class="bg-base-200 rounded-lg p-4 flex justify-between items-center">
      <div>
        <h4 class="text-sm font-semibold"><%= t(".total_users") %></h4>
        <p class="text-xl font-bold"><%= @role.users_count %></p>
      </div>
      <i class="fas fa-users text-2xl text-primary"></i>
    </div>

    <div class="bg-base-200 rounded-lg p-4 flex justify-between items-center">
      <div>
        <h4 class="text-sm font-semibold"><%= t(".permissions") %></h4>
        <p class="text-xl font-bold"><%= @role.permissions.count %></p>
      </div>
      <i class="fas fa-shield-alt text-2xl text-accent"></i>
    </div>

    <div class="bg-base-200 rounded-lg p-4 flex justify-between items-center">
      <div>
        <h4 class="text-sm font-semibold"><%= t(".last_modified") %></h4>
        <p class="text-sm"><%= l(@role.updated_at, format: :long) %></p>
      </div>
      <i class="fas fa-history text-2xl text-secondary"></i>
    </div>
  </div>
</div>

<div class="bg-base-100 shadow rounded-lg p-6 mt-6">
  <div class="flex justify-between items-center mb-6">
    <div>
      <h3 class="text-lg font-medium mb-1">
        <%= t(".assigned_users") %>
      </h3>

      <p class="text-sm text-gray-600 mb-4">
        <%= t(".manage_users_with_this_role") %>
      </p>
    </div>

    <div class="mb-6">
        <% if can? :create, UsersRole %>
            <button onclick="document.getElementById('add_users_modal_<%= @role.id %>').showModal()" class="btn btn-accent btn-outline cursor-pointer">
                <i class="fas fa-plus mr-2"></i>
                <%= t("admin.roles.show.add_user") %>
            </button>

            <%= render partial: 'admin/roles/user_roles/new', locals: { role: @role } %>
        <% end %>
    </div>
</div>


  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    <% @role.users_roles.each do |users_role| %>
      <div class="bg-base-200 rounded-lg p-4 flex items-center justify-between space-x-3">
        <div class="flex items-center space-x-3">
          <%= render(UserAvatarComponent.new(user: users_role.user, size: 30)) %>
          <span class="text-sm font-medium"><%= users_role.user.decorate.full_name %></span>
        </div>

        <% if can? :destroy, UsersRole %>
          <%= button_to admin_role_user_role_path(@role, users_role), method: :delete, data: { turbo_confirm: t('admin.user_roles.confirm_removal', role_name: @role.name) }, class: "btn btn-sm btn-gost text-error" do %>
            <i class="fas fa-trash"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

<div class="bg-base-100 shadow rounded-lg p-6 mt-6">
  <div class="flex justify-between items-center mb-6">
    <div>
      <h3 class="text-lg font-medium mb-1">
        <%= t(".role_permissions_title") %>
      </h3>
      <p class="text-sm mb-4">
        <%= t(".manage_role_permissions_subtitle") %>
      </p>
    </div>

    <div class="mb-6">
      <% if can? :create, RolesPermission %>
        <button onclick="document.getElementById('add_permissions_modal_<%= @role.id %>').showModal()" class="btn btn-accent btn-outline cursor-pointer">
            <i class="fas fa-plus mr-2"></i>
            <%= t("admin.roles.show.add_permission") %>
        </button>

        <%= render partial: 'admin/roles/roles_permissions/new', locals: { role: @role } %>
      <% end %>
   </div>
</div>

<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
    <% @role.roles_permissions.each do |role_permission| %>
      <div class="bg-base-200 rounded-lg p-4 flex items-center justify-between space-x-3">
        <div class="flex items-center space-x-3">
          <i class="fas fa-key text-gray-600"></i>
          <span class="text-sm font-medium"><%= role_permission.permission.name.titleize %></span>
        </div>
        <% if can? :destroy, RolesPermission %>
          <%= button_to admin_role_roles_permission_path(@role, role_permission), method: :delete, data: { turbo_confirm: t('admin.roles_permissions.confirm_removal', role_name: @role.name) }, class: "btn btn-sm btn-gost text-error" do %>
            <i class="fas fa-trash"></i>
          <% end %>
        <% end %>
      </div>
    <% end %>
</div>